
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adopta_frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: adopta_backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/adopta_db
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: adopta_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
